# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-11 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0002_auto_20180906_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='publichealthservices',
            name='implants',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
