# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-11 10:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0003_publichealthservices_implants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publichealthservices',
            name='ccmdd_pick',
            field=models.CharField(blank=True, max_length=15, verbose_name=b'CCMDD Pick Up Point'),
        ),
        migrations.AlterField(
            model_name='publichealthservices',
            name='implants',
            field=models.BooleanField(verbose_name=b'Implants (Contraception)'),
        ),
    ]
