# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-11 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0004_auto_20180911_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publichealthservices',
            name='ccmdd_pick',
            field=models.CharField(blank=True, max_length=50, verbose_name=b'CCMDD Pick Up Point'),
        ),
    ]
