# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-12-11 14:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0004_auto_20181211_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducation',
            name='name',
            field=models.CharField(max_length=255, verbose_name='School Name'),
        ),
    ]
