# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-08 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0005_auto_20181211_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='highereducation',
            name='institution',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
