# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-12 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0006_auto_20180912_1330'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mariestopesfacilities',
            table='marie_stopes_services',
        ),
    ]
