# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-12 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0008_auto_20180912_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatepharmacies',
            name='unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
