# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-12 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0009_privatepharmacies_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatepharmacies',
            name='address',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
