# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-13 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0011_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthFacilities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('settlement', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('facility_code', models.CharField(max_length=20, unique=True)),
                ('parent_geo_code', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
