# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2019-01-24 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0011_auto_20190115_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerbasiceducation',
            name='activity_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='partnerlocation',
            name='activity_number',
            field=models.IntegerField(default=0),
        ),
    ]
