# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0012_auto_20190124_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='donor_agency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='other_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
