# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-13 14:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0012_healthfacilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacilities',
            name='data',
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthfacilities',
            name='dataset',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='healthfacilities',
            unique_together=set([('name', 'latitude', 'longitude')]),
        ),
        migrations.AlterModelTable(
            name='healthfacilities',
            table='health_facilities',
        ),
    ]
