# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0013_auto_20190208_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='areaimplementation',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='areaimplementation',
            name='organisation',
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='contact',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partnerbasiceducation',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partnerhealth',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partnerhighereducation',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='partnerlocation',
            name='organisation',
        ),
        migrations.RemoveField(
            model_name='target',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='target',
            name='organisation',
        ),
        migrations.DeleteModel(
            name='Activity',
        ),
        migrations.DeleteModel(
            name='AreaImplementation',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Organisation',
        ),
        migrations.DeleteModel(
            name='PartnerBasicEducation',
        ),
        migrations.DeleteModel(
            name='PartnerHealth',
        ),
        migrations.DeleteModel(
            name='PartnerHigherEducation',
        ),
        migrations.DeleteModel(
            name='PartnerLocation',
        ),
        migrations.DeleteModel(
            name='Target',
        ),
    ]
