# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-14 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0013_auto_20180913_1624'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthfacilities',
            old_name='data',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
