# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0014_auto_20180914_1308'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MarieStopes',
        ),
        migrations.RemoveField(
            model_name='mariestopesfacilities',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='pharmacyservices',
            name='facility',
        ),
        migrations.DeleteModel(
            name='PrivatePharmacies',
        ),
        migrations.DeleteModel(
            name='PublicHealthFacilities',
        ),
        migrations.RemoveField(
            model_name='publichealthservices',
            name='facility',
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
        migrations.DeleteModel(
            name='MarieStopesFacilities',
        ),
        migrations.DeleteModel(
            name='PharmacyServices',
        ),
        migrations.DeleteModel(
            name='PublicHealthServices',
        ),
    ]
