# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0015_auto_20180917_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthfacilities',
            name='parent_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
