# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 12:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0018_auto_20180917_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacilities',
            name='parent_geo_code',
        ),
        migrations.AddField(
            model_name='healthfacilities',
            name='geo_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20), default=[], size=None),
            preserve_default=False,
        ),
    ]
