# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 13:53
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0019_auto_20180917_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='geo_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=20, null=True), size=None),
        ),
    ]
