# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2018-09-17 14:00
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0020_auto_20180917_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='geo_levels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, size=None),
        ),
    ]
