# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-18 07:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0022_auto_20180917_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='HigherEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('facility_code', models.CharField(max_length=100, unique=True)),
                ('classification', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('dataset', models.CharField(max_length=20)),
                ('geo_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('service', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'higher_education',
            },
        ),
        migrations.AlterUniqueTogether(
            name='highereducation',
            unique_together=set([('name', 'latitude', 'longitude')]),
        ),
    ]
