# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-19 14:49
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0023_auto_20180918_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=7)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('sector', models.CharField(blank=True, max_length=20)),
                ('phase', models.CharField(blank=True, max_length=20)),
                ('dataset', models.CharField(max_length=20)),
                ('facility_code', models.CharField(max_length=100, unique=True)),
                ('geo_levels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None)),
                ('service', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
            options={
                'db_table': 'basic_education',
            },
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'School Name'),
        ),
        migrations.AlterUniqueTogether(
            name='basiceducation',
            unique_together=set([('name', 'latitude', 'longitude')]),
        ),
    ]
