# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-19 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0024_auto_20180919_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiceducation',
            name='dataset',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='basiceducation',
            name='sector',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
