# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-21 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0025_auto_20180919_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthfacilities',
            name='latitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='longitude',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
