# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-25 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0026_auto_20180921_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiceducation',
            name='special_need',
            field=models.CharField(default='No', max_length=5),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='healthfacilities',
            unique_together=set([('name', 'latitude', 'longitude', 'facility_code')]),
        ),
    ]
