# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-26 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0027_auto_20180925_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiceducation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='basiceducation',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='healthfacilities',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
