# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-09-27 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0029_auto_20180927_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthfacilities',
            name='parent_name',
        ),
    ]
