# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0031_auto_20181003_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_number', models.IntegerField()),
                ('hiv_aids_focus', models.BooleanField(verbose_name='Main Focus on HIV/AIDS')),
                ('category', models.CharField(max_length=100, verbose_name='Implementation activity category')),
                ('other_catrgory', models.CharField(max_length=100)),
                ('donar_agency', models.CharField(max_length=100)),
                ('activity', models.CharField(max_length=255)),
                ('she_conquers_element', models.CharField(max_length=100)),
                ('other_she_conquers', models.CharField(max_length=255)),
                ('timeline', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'partner_activity',
            },
        ),
        migrations.CreateModel(
            name='AreaImplementation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_type', models.CharField(max_length=255)),
                ('other_location_type', models.CharField(max_length=255)),
                ('province', models.CharField(max_length=20)),
                ('more_province', models.CharField(max_length=20)),
                ('district_municiplaity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'partner_contact',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('logo', models.FileField(upload_to=b'')),
            ],
            options={
                'db_table': 'partner_orgainisation',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audience', models.CharField(max_length=255)),
                ('other_audience', models.CharField(max_length=255)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap_health.Organisation')),
            ],
            options={
                'db_table': 'partner_target',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap_health.Organisation'),
        ),
        migrations.AddField(
            model_name='areaimplementation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap_health.Organisation'),
        ),
        migrations.AddField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wazimap_health.Organisation'),
        ),
        migrations.AlterUniqueTogether(
            name='contact',
            unique_together=set([('organisation', 'name')]),
        ),
    ]
