# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0032_auto_20181029_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
