# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-29 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0033_auto_20181029_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='donar_agency',
            new_name='donor_agency',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='other_catrgory',
            new_name='other_category',
        ),
        migrations.AlterField(
            model_name='activity',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='wazimap_health.Organisation'),
        ),
        migrations.AlterField(
            model_name='areaimplementation',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='wazimap_health.Organisation'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='wazimap_health.Organisation'),
        ),
        migrations.AlterField(
            model_name='target',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='wazimap_health.Organisation'),
        ),
    ]
