# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0034_auto_20181029_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaimplementation',
            name='district_municiplaity',
            field=models.CharField(max_length=255),
        ),
    ]
