# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 10:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0037_auto_20181030_1203'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='areaimplementation',
            table='partner_area_implementation',
        ),
    ]
