# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0038_auto_20181030_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='areaimplementation',
            old_name='district_municiplaity',
            new_name='district',
        ),
        migrations.AddField(
            model_name='areaimplementation',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
