# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0039_auto_20181030_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaimplementation',
            name='municipality',
            field=models.TextField(blank=True, null=True),
        ),
    ]
