# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-10-30 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0040_auto_20181030_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerBasicEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('school', models.CharField(max_length=50)),
                ('activity_number', models.CharField(max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basic_ed', to='wazimap_health.Organisation')),
            ],
            options={
                'db_table': 'partner_basic_education_facilities',
            },
        ),
        migrations.CreateModel(
            name='PartnerHealth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('facility', models.CharField(max_length=50)),
                ('activity_number', models.CharField(max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health', to='wazimap_health.Organisation')),
            ],
            options={
                'db_table': 'partner_health_facilities',
            },
        ),
        migrations.CreateModel(
            name='PartnerHigherEducation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province', models.CharField(max_length=50)),
                ('institution', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=100)),
                ('activity_number', models.CharField(max_length=10)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='higher_ed', to='wazimap_health.Organisation')),
            ],
            options={
                'db_table': 'partner_higher_education_facilities',
            },
        ),
    ]
