# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-01 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0042_auto_20181101_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highereducation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='highereducation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
