# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-01 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0043_auto_20181101_1035'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='highereducation',
            unique_together=set([('name', 'latitude', 'longitude', 'institution')]),
        ),
    ]
