# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-11-12 18:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wazimap_health', '0048_auto_20181112_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='areaimplementation',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_activity', to='wazimap_health.Activity'),
        ),
        migrations.AddField(
            model_name='target',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target_activity', to='wazimap_health.Activity'),
        ),
    ]
